### ISSUE TITLE
Filter by more than one group

### ISSUE THREAD

**Issue by bioslikk** [mlimaloureiro/ansible-rackhd-inventory#3]
It was requested that dynamic inventories script should allow to filter by more than one group, i.e, retrieve the nodes that belong to two groups. e.g., We could want the nodes that belong to the groups "ceph-node" or "ceph-mon" and the group "new".
This change would allow us to append a new field in the config.yaml file named "filter_group" with a string value. We could go even further and change the way we define the "filter_group" to a list of strings to allow filtering by more than one group if needed be.

**Comment by mlimaloureiro** [comment]
yep, it's a must for our internal projects now
