### ISSUE TITLE
If there are no groups defined in the config.yaml file we should get all groups

### ISSUE THREAD

**Issue by bioslikk** [mlimaloureiro/ansible-rackhd-inventory#6]
As the tittle suggest, if there are no groups specified in the config.yaml file we should retrieve all groups in the RackHD. However, from my readings of the RackHD api [documentation](https://rackhd.readthedocs.io/en/latest/rackhd_api/nodes.html#), we can get the list of tags with GET "/api/current/tags" and then for each tag GET the nodes that belong to that group. This works, howbeit, it is very inefficient. We should get all the nodes in RackHD with one call and the groups that that node belongs to should be included in the objects retrieved. Does something like "/api/current/tags/nodes" or "/api/current/nodes/tags" exist ?

**Comment by mlimaloureiro** [comment]
from my understanding, you can only get the tags from a node but please check in the docs

```
curl -H "Content-Type: application/json" -X GET $(RHD_HOST)/api/current/nodes/$(NODE_ID)/tags
```

anyway, performance isn't an issue here. prioritize readability over performance for now
